<a href="https://colab.research.google.com/github/SummerLife/Embedded-ML/blob/master/project/09_minist_numpy/minist_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from mnist import load_mnist
import numpy as np
from PIL import Image
import pickle

ModuleNotFoundError: ignored

In [6]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

NameError: ignored

In [ ]:
x_train.shape, t_train, t_train.shape, x_test.shape, x_test.shape, t_test, t_test.shape

In [ ]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [ ]:
img = x_train[0]
label = t_train[0]
print(label)

In [ ]:
print(img.shape)

In [ ]:
img = img.reshape(28, 28)

In [ ]:
img.shape

In [ ]:
img_show(img)

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(img)

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 

    x = x - np.max(x) # handle overflow
    return np.exp(x) / np.sum(np.exp(x))

In [ ]:
def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test

In [ ]:
def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)

    return network

In [ ]:
def predict(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)

    return y

In [ ]:
x, t = get_data()

In [ ]:
network = init_network()

In [ ]:
accuracy_cnt = 0

In [ ]:
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y) # gets the index of the element with the highest probability
    if p == t[i]:
        accuracy_cnt += 1

print(accuracy_cnt)
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

In [ ]:
W1, W2, W3 = network["W1"], network["W2"], network["W3"]

In [ ]:
x.shape

In [ ]:
x[0].shape

In [ ]:
W1.shape

In [ ]:
W2.shape

In [ ]:
W3.shape

In [ ]:
x, t = get_data()
network = init_network()

batch_size = 2000
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    print(i)
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    print(p)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))


In [ ]:
x = np.array([[0.1,0.8,0.1], [0.3,0.1,0.6], [0.2,0.5,0.3], [0.7,0.2,0.1]])

In [ ]:
np.argmax(x, axis=1)

In [ ]:
np.argmax(x, axis=0)

In [ ]:
y = np.array([1,2,1,0])
t = np.array([1,2,0,0])

In [ ]:
print(y==t)

In [ ]:
np.sum(y==t)

In [1]:
import numpy as np

def mean_squared_error(y, t):
    return 0.5 * np.sum(np.subtract(y,t) **2)

In [2]:
t = [0,0,1,0,0,0,0,0,0,0]

In [3]:
y = [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0]
print(len(y))

10


In [4]:
mean_squared_error(y, t)

0.09750000000000003

In [5]:
y = [0.1,0.05,0.1,0.0,0.05,0.1,0.0,0.6,0.0,0.0]

In [6]:
mean_squared_error(y, t)

0.5975

In [7]:
np.subtract(y, t)**2

array([0.01  , 0.0025, 0.81  , 0.    , 0.0025, 0.01  , 0.    , 0.36  ,
       0.    , 0.    ])

In [8]:
# cross entropy error

In [9]:
def cross_entry_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [10]:
cross_entry_error(np.array(y), np.array(t))

2.302584092994546

In [11]:
t = [0,0,1,0,0,0,0,0,0,0]
y = [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0]

In [12]:
cross_entry_error(np.array(y), np.array(t))

0.510825457099338

In [13]:
np.random.choice(60000, 10)

array([40752, 28971, 57654, 29893, 12807, 53193, 10253, 19845, 58530,
       49002])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
def cross_entry_error_mul(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batche_size = y.shape[0]
    return -np.sum()

In [35]:
y = np.array([0,1,2,3,4,5])

In [36]:
y

array([0, 1, 2, 3, 4, 5])

In [37]:
y.ndim

1

In [38]:
y.reshape(1, y.size)

array([[0, 1, 2, 3, 4, 5]])

In [39]:
y.reshape(1, y.size).ndim

2

In [40]:
y.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
y.reshape(2, 3).ndim

2

In [42]:
y.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
y = [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0]

In [44]:
array_y = np.array(y)

In [46]:
array_y

array([0.1 , 0.05, 0.6 , 0.  , 0.05, 0.1 , 0.  , 0.1 , 0.  , 0.  ])

In [47]:
array_y.shape

(10,)

In [60]:
y = [[0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0],
     [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0],
     [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0],
     [0.1,0.05,0.6,0.0,0.05,0.1,0.0,0.1,0.0,0.0]
     ]

t = [2,7,0,9]

In [61]:
np.array(y)[np.arange(4), np.array(t)]

array([0.6, 0.1, 0.1, 0. ])

In [62]:
np.array([np.arange(4), np.array(t)])

array([[0, 1, 2, 3],
       [2, 7, 0, 9]])